version: '3.8'
services:
  redis:
    image: redis:7
    container_name: syncore-redis
    ports:
      - '6379:6379'
  app:
    build: .
    container_name: syncore-app
    depends_on:
      - redis
      - ftp
      - mailhog
    ports:
      - '8080:8080'
    environment:
      - SPRING_REDIS_HOST=redis
  ftp:
    image: fauria/vsftpd
    container_name: syncore-ftp
    ports:
      - '21:21'
      - '21000-21010:21000-21010'
    environment:
      - FTP_USER=demo
      - FTP_PASS=demo
      - PASV_ADDRESS=127.0.0.1
      - PASV_ADDR_RESOLVE=false
      - PASV_ENABLE=true
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
      - LOG_STDOUT=1
    volumes:
      - ./ftp-data:/home/vsftpd
  mailhog:
    image: mailhog/mailhog
    container_name: syncore-mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
