version: '3.8'
services:
  redis:
    image: redis:7
    container_name: syncore-redis
    ports:
      - '6379:6379'
  app:
    build: .
    container_name: syncore-app
    depends_on:
      - redis
    ports:
      - '8080:8080'
    environment:
      - SPRING_REDIS_HOST=redis
