server:
  port: 8080

spring:
  application:
    name: syncore
  redis:
    host: redis
    port: 6379
logging:
  level:
    root: INFO


syncore:
  ftp:
    host: ftp
    port: 21
    user: demo
    pass: demo
    poll-interval-ms: 30000
  report:
    to: dev@example.com

spring:
  mail:
    host: mailhog
    port: 1025
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
